# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarker',
            name='jobTitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
