# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarkapp', '0003_industry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='resources',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
